### ISSUE TITLE
ERROR: Only one copy of bitbake should be run against a build directory

### ISSUE THREAD

**Issue by EugenWiens** [EugenWiens/vscode-bitbake#16]

**Comment by ShrivanRaj** [comment]
I did faced the same error in my case also, "ERROR: Only one copy or bitbake should run against a build directory".

For this issue we need to delete the already running bitbake process in the system. Hence the existing bitbake process could not able to start, because the same process name already exists.

Step 1:
If you are running with the docker first exit from that by using the command "exit". Now the prompt will shows like "shrjayab@devserver:" instead of "shrjayab@devserver-docker:"

Step 2:
After that do the following command,
"ps -ef|grep bitbake". This command will tel you about the pid id and other details about the process.

Step 3:
Now do the kill command,
"kill -9 [PPID]".

Step 4:
Now you get into the docker and try to run again.

**Comment by EugenWiens** [comment]
Thank you for confirming the error and the solutions. 

My idea would be to avoid this lock. The bitbake plugin can use the bitbake command in another folder instead **build**.

Until now I was not able to manage the underlying library to execute `. ./oe-init-build-env vsc > /dev/null ; ${command}`. My idea is to use the **vsc** folder for the plugin.

**Comment by prisuna2015** [comment]
I'm killing the process but its showing again the same error. Could you please help with this issue.
Thanks in advance.

**Comment by EugenWiens** [comment]
Hi,
Maybe it helps to delete the bitbacke lock file.

Anyway I'm working on this error. But my time is currently rare.

Best regards,
Eugen

prisuna2015 <notifications@github.com> schrieb am Sa., 13. Jan. 2018, 10:10:

**Comment by etexley** [comment]
The root cause of this problem is the build/bitbake.lock file.   Ideally if the bitbake team wanted to create an intermittent lock file, they would handle a graceless interrupt (sighup for instance if I'm telnet in)  and remove this file themselves when the python processes die.   Just remove the file and you're good to go.

**Comment by EugenWiens** [comment]
Yesterday I released [V0.0.13](https://github.com/EugenWiens/vscode-bitbake/releases/tag/V0.0.13) this version includes a feature that uses an extra folder for `bitbake` operations. From now it is possible to work with `vscode-bitbake` and at the same time with `bitbake` on terminal.
